### ISSUE TITLE
XApiObject class has `type` property which is an "[...] Unknown key [...]"

### ISSUE THREAD

**Issue by LennartCode** [rwth-acis/i5-Toolkit-for-Unity#21]
**Describe the bug**
When creating a call to the LRS in simple mode, a call can get a HTTP 400 response with the message: `{"errorId":"IDHERE","warnings":["Unknown keys (type) set in 'statements.0.object'"]}`.
Before that, this is printed to the Unity console: `[i5.Toolkit.Core.ExperienceAPI.ExperienceAPIClient] Sending xAPI statement mailto:anonymoususer@viaproma.com : http://id.tincanapi.com/verb/selected : http://github.com/RepositoryOwner/Repository/issues/12345`

Steps to reproduce (and a little analysis):

1. Initialize a `ExperienceAPIClient` with it's version, endpoint and authToken
2. Initialize an object of each of the types `Actor`, `Verb` and `XApiObject` with suitable parameters
3. Call `clientInstance.SendStatementAsync(new Statement(actor, verb, xApiObject))`
4. Observe in Unity's debug console: `{"errorId":"IDHERE","warnings":["Unknown keys (type) set in 'statements.0.object'"]}`

In the process of calling the API, the class `XApiObject` is instantiated. It has the property `type` which is never used. When the object is serialized to JSON it looks like this:

```jsonc
{
  // ...
  "object": {
    "id": "IDHERE",
    "type": ""
  }
}
```
Which can be retrieved by setting a breakpoint in \Experience API\Scripts\ExperienceAPIClient.cs:106 and taking a look at the `json` variable. Sending the exact same request with Postman yields that the attribute `type` is the only thing preventing the request from succeeding. I assume that it was meant to be included as a child of the `description` attribute, resulting in this:

```jsonc
{
  // ...
  "object": {
    "id": "IDHERE",
    "description": {
      // ...
      "type": "TYPEEHERE"
    }
  }
}
```

Just removing the `type` attribute should resolve this bug.

**Expected behavior**
The method `SendStatementAsync()` (with any attributes, as they are equivalent) should succeed in creating an entry in the LRS.

**Bug Observed on the Following Build Targets**
Check applicable build targets by putting an x in-between the square brackets.
- [x] Unity editor
- [ ] PC, Mac, Standalone
- [ ] Universal Windows Platform (UWP)
- [ ] iOS
- [ ] Other (please specify): 

**For deployed applications, please provide information about the device on which the bug occurred**
Unity v2021.3.10f1

**Additional context**
This bug ocured while working on VIAProMa

**Comment by BenediktHensen** [comment]
The type variable is indeed misplaced and should instead be part of a "definition" child-object. For now, I have set the type variable to non-serialized as it is still used by the advanced mode.
